### PR TITLE
Added Spanish (Castillian) Language

### PR DESCRIPTION
**Pull request by krinkuto11**
Added the Spanish (Castillian) language following the guidelines in the readme

### CODE REVIEW

**Comment by danielbrendel** [comment]
Hi, thank you for your PR. Looks good so far, but can you rename the folder so it does comply with [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1)? I'll add that requirement to the localization contribution guidelines.
In your case you'd just rename the folder to `es` so it is a two-letter code folder name.

**Comment by danielbrendel** [comment]
Hi, this looks good so far! Just one more question:
```
~/.DS_Store
```

Why is the tilde neccessary? Or is that part of the name? I didn't find anything in the gitignore documentation and I am not on macOS, so I am just curious. :D 

I gonna merge this in the next days.

**Comment by krinkuto11** [comment]
I think I made a mistake by thinking it was necesary for Github to ignore the file in every folder. Maybe putting "**/.DS_Store" instead would be the right thing to do? As you might have guessued I'm still a bit new in the game.

**Comment by danielbrendel** [comment]
Yep, `**/.DS_Store` would work. Using tilde however does not exclude the file. You can verify this if you e.g. use VS Code as your editor as it does integrate with git well and visually shows you what files are staged for commit.

You can change this in a new commit, then I can merge it. :)

**Comment by krinkuto11** [comment]
Thanks for the guidance. Entry changed :)

**Review by danielbrendel — APPROVED** [review]
Looks good.

**Pull request merged**
